name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Git
      run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub CI"

    - name: Build SportPaper
      run: bash sportpaper build
    - name: Upload SportPaper JAR
      uses: actions/upload-artifact@v4
      with:
        name: sportpaper-1.8.8-R0.1-SNAPSHOT.jar
        path: SportPaper-Server/target/sportpaper-1.8.8-R0.1-SNAPSHOT.jar
        if-no-files-found: error
